name: Release

on:
  push:
    branches: [ $default-branch ]
    tags:
      - 'v*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          npm ci
      - name: Lint
        run: |
          npm run lint
      - name: Unit-tests
        run: |
          npm run unit-test
      - name:
          Coverage
          # Could be replaced with coverage-all if you want to ensure new files are tested as well
        run: |
          npm run coverage
      - name: E2E-tests
        uses: cypress-io/github-action@v2
        env:
          USERSCRIPTER_MODE: production
        with:
          build: npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          BRANCH: gh-pages
          FOLDER: dist
